name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  NuGet-Publish:
    runs-on: ubuntu-latest
    steps:

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Download Build
        run: wget https://nightly.link/KonataDev/Konata.Codec/workflows/nightly-build.yaml/main/nightly.zip

      - name: Unpack Artifact
        run: unzip nightly.zip && ls -al .

      - name: Add private GitHub registry to NuGet
        run: dotnet nuget add source --username TheSnowfield --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/KonataDev/index.json"

      - name: Publish
        run: |
          dotnet nuget push ./Konata.Codec*.nupkg --source "github" --skip-duplicate --api-key ${{ secrets.GIT_TOKEN }}
          dotnet nuget push ./Konata.Codec*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{ secrets.NUGETAPIKEY }}

